<a href="https://colab.research.google.com/github/Cuongtran241004/Numpy/blob/main/01_Numpy_Introduction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
arr = np.array([[1,2,3], [4,5,6]])
print("Array is of type: ", type(arr))
print("Dimension: ", arr.ndim)
print("Shape: ", arr.shape)
print("Size: ", arr.size)
print("Array type: ", arr.dtype)

In [ ]:
import numpy as np
a = np.array([[1,2,4], [5,8,7]], dtype = 'float')
print("Array created using passed list: \n", a)
print("Array type: ", a.dtype)

b = np.array((1, 3, 2), dtype="int")
print("\nArray created using passed tuple: \n", b)

c = np.zeros((3, 4))
print("\nAn array initialized with all zeros: \n", c)

c = np.ones((3, 4), dtype="int")
print("\nAn array initialized with all one: \n", c)

d = np.full((3, 3), 6, dtype='complex')
print("\nAn array with full 6: \n", d)

d = np.empty((3, 3), dtype="int")
print("\nAn array with empty: \n", d)

e = np.random.random((2, 2))
print("\nA random array: \n", e)

f = np.arange(0, 30, 5)
print("\nAn array with step of 5: \n", f)

g = np.linspace(0, 100, 5, dtype="int")
print("\nA sequential array with 10 values between 0 and 5: \n", g)

In [18]:
import numpy as np
arr = np.array([[1, 2, 3, 4],
                [5, 2, 4, 2],
                [1, 2, 0, 1]])
# reshape(count, row, column)
newArr = arr.reshape(2, 2, 3)
print("New array: \n", newArr)

[[[1 2 3]
  [4 5 2]]

 [[4 2 1]
  [2 0 1]]]
